# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OasisMembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Email', models.EmailField(max_length=254)),
                ('Ability1', models.CharField(choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 1')),
                ('Ability2', models.CharField(choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 2')),
                ('Ability3', models.CharField(choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 3')),
                ('Ability4', models.CharField(choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 4')),
                ('Location', models.CharField(max_length=200)),
                ('IsLeader', models.BooleanField(default=False, verbose_name='Leader')),
                ('CourseContribution', models.TextField(verbose_name='Course Contribution')),
                ('IsCurrent', models.BooleanField(default=True, verbose_name='Current Member')),
                ('NumberOfGuides', models.IntegerField(default=1, verbose_name='Number of Guides')),
                ('LifePurpose', models.TextField(verbose_name='Life Purpose')),
                ('HasSpotlight', models.BooleanField(default=False, verbose_name='Spotlight')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='Notes',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='attendee',
            name='Meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OasisMembers.Meeting'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OasisMembers.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='CoCoordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MeetingsCoCoordinated', to='OasisMembers.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MeetingsCoordinated', to='OasisMembers.Member'),
        ),
    ]
