# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OasisMembers', '0002_auto_20170702_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Notes',
            field=models.TextField(default=''),
        ),
    ]
