# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OasisMembers', '0003_member_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CourseContribution',
            field=models.TextField(blank=True, verbose_name='Course Contribution'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='LifePurpose',
            field=models.TextField(blank=True, verbose_name='Life Purpose'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='Notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
