# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OasisMembers', '0004_auto_20170717_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Ability1',
            field=models.CharField(blank=True, choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Ability2',
            field=models.CharField(blank=True, choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Ability3',
            field=models.CharField(blank=True, choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 3'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Ability4',
            field=models.CharField(blank=True, choices=[('Feeling', 'Feeling'), ('Hearing', 'Hearing'), ('Knowing', 'Knowing'), ('Vision', 'Vision')], max_length=8, verbose_name='Ability 4'),
        ),
    ]
