# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OasisMembers', '0005_auto_20170717_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='CoCoordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MeetingsCoCoordinated', to='OasisMembers.Member'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='Coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MeetingsCoordinated', to='OasisMembers.Member'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='Notes',
            field=models.TextField(blank=True),
        ),
    ]
