# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OasisMembers', '0006_auto_20170718_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['FirstName', 'LastName']},
        ),
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ['Name']},
        ),
        migrations.AddField(
            model_name='attendee',
            name='IsCoordinator',
            field=models.BooleanField(default=False, verbose_name='Coordinator'),
        ),
    ]
